name: Build cuda-ecm

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-cuda-ecm:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          tool-cache: false

      - name: Setup CUDA
        uses: Jimver/cuda-toolkit@28e983fc6bf47e7a732934aa029a6738e2ce16e4
        id: cuda-toolkit
        with:
          cuda: '12.6.2'

      - run: cmake .

      - run: make -j $(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: cuda-ecm
          path: bin/cuda-ecm

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/cuda-ecm
